spring.application.name=AirBNB
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/AirBNB
spring.datasource.username=postgres
spring.datasource.password=112233
server.servlet.context-path=/api/v1